version: "3.8"
services:
  db:
    image: mysql:8.0.28-oracle
    environment:
      MYSQL_ROOT_PASSWORD: Renegade187!
      MYSQL_DATABASE: discord-api
    restart: always
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "9090:8080"
  api:
    image: node:17.9.0-alpine3.15
    environment:
      MYSQL_DATABASE: discord-api
      MYSQL_USER: root
      MYSQL_PASSWORD: Renegade187!
      MYSQL_HOST: db
    working_dir: /app/src
    entrypoint: ["/bin/sh", "-c" , "npm install -g nodemon && npm install && nodemon index.js"]
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure